"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { useState } from "react";

import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarExpanded, setIsSidebarExpanded] = useState(false);
  const [isManuallyExpanded, setIsManuallyExpanded] = useState(false);

  const toggleSidebar = () => {
    setIsSidebarExpanded((prev) => !prev);
    setIsManuallyExpanded((prev) => !prev);
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <div className="flex min-h-screen">
            <Sidebar
              isExpanded={isSidebarExpanded}
              toggleSidebar={toggleSidebar}
              isManuallyExpanded={isManuallyExpanded}
            />

            <div
              className={`flex-1 pl-0 lg:pl-20 ${
                isSidebarExpanded
                  ? "left-0 lg:left-64 w-[calc(100%-0rem)] lg:w-[calc(100%-16rem)]"
                  : "left-0 lg:left-20 w-[calc(100%-0rem)] lg:w-[calc(100%-5rem)]"
              }`}
            >
              <Header
                isSidebarExpanded={isSidebarExpanded}
                toggleSidebar={toggleSidebar}
              />
              <main
                className={`mt-16 px-0 py-4 lg:px-6 xl:px-8 2xl:px-10 w-[100%] min-h-[calc(100vh-5rem)] bg-[#5a58580b]`}
              >
                {children}
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
